# ============================================================
#  CONFIGURACION SUPABASE (Session Pooler - puerto 5432)
# ============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.jxvbbrlrfwzxmrtuycjr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lwwBaetRzn2tOhFz}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
#  HIKARI
# ============================================================
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# ============================================================
#  JPA / HIBERNATE
# ============================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ============================================================
#  SERVIDOR
# ============================================================
server.port=${SERVER_PORT:8080}

# ============================================================
#  SWAGGER / SPRINGDOC
# ============================================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha