# ============================================================
#  CONFIGURACION SUPABASE (Session Pooler - IPv4 compatible)
# ============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.jxvbbrlrfwzxmrtuycjr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lwwBaetRzn2tOhFz}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
#  JPA / HIBERNATE
# ============================================================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
#  SERVIDOR
# ============================================================
server.port=${SERVER_PORT:8080}

# ============================================================
#  SWAGGER / SPRINGDOC
# ============================================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha