
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?
spring.datasource.username=postgres.jxvbbrlrfwzxmrtuycjr
spring.datasource.password=lwwBaetRzn2tOhFz
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
#  JPA / HIBERNATE
# ============================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
#  SERVIDOR
# ============================================================
server.port=8080

# ============================================================
#  SWAGGER / SPRINGDOC
# ============================================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
